import Head from "next/head";
import { Fragment } from "react";
import { Header } from "./components/Header";

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Instageram App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* header */}
      <Header />
      {/* feed */}
      {/* modal */}
    </Fragment>
  );
}
